#!/usr/bin/env python3
"""Generate cross-platform text-expansion adapters from the command registry."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "text-replacements" / "manifest.json"
ESPANSO_PATH = ROOT / "text-replacements" / "espanso" / "maestro-mini.yml"


def yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def command_label(command: str) -> str:
    return command.replace("-", " ").title()


def load_entries() -> list[dict[str, str]]:
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    entries = manifest["replacements"]
    if not isinstance(entries, list):
        raise ValueError("manifest replacements must be a list")
    return entries


def render_match(trigger: str, replacement: str, label: str, command: str) -> list[str]:
    lines = [
        f"  - trigger: {yaml_string(trigger)}",
        f"    replace: {yaml_string(replacement)}",
        f"    label: {yaml_string(label)}",
        f"    search_terms: [{yaml_string(command)}, {yaml_string(trigger)}]",
    ]
    if trigger.isalnum():
        lines.append("    word: true")
    return lines


def render_espanso(entries: list[dict[str, str]]) -> str:
    lines = [
        "# Generated by scripts/generate_expansions.py. Edit manifest.json instead.",
        "matches:",
    ]
    for entry in entries:
        command = entry["command"]
        lines.extend(
            render_match(
                entry["trigger"],
                entry["replacement"],
                f"Maestro Mini — {command_label(command)}",
                command,
            )
        )
    for entry in entries:
        command = entry["command"]
        lines.extend(
            render_match(
                ";cmd",
                entry["replacement"],
                f"{command_label(command)} — {entry['trigger']}",
                command,
            )
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated output is stale")
    args = parser.parse_args()

    rendered = render_espanso(load_entries())
    if args.check:
        if not ESPANSO_PATH.exists() or ESPANSO_PATH.read_text(encoding="utf-8") != rendered:
            print(f"stale generated file: {ESPANSO_PATH}", file=sys.stderr)
            return 1
        print(f"generated adapter is current: {ESPANSO_PATH}")
        return 0

    ESPANSO_PATH.parent.mkdir(parents=True, exist_ok=True)
    ESPANSO_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {ESPANSO_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
